apiRules: 
- exclude:
    uidRegex: AnonymousTypes
    type: Namespace
- exclude:
    uidRegex: DotNetForHtml5
    type: Namespace
- exclude:
    uidRegex: DotNetForHtml5.Core
    type: Namespace
- exclude:
    uidRegex: JSIL
    type: Namespace
- exclude:
    uidRegex: JSIL.Meta
    type: Namespace
- exclude:
    uidRegex: CSHTML5
    type: Namespace
- exclude:
    hasAttribute:
      uid: ObsoleteAttribute
- exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute