### YamlMime:ManagedReference
items:
- uid: System.Xaml.Markup.IValueSerializerContext
  commentId: T:System.Xaml.Markup.IValueSerializerContext
  id: IValueSerializerContext
  parent: System.Xaml.Markup
  children:
  - System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Reflection.PropertyInfo)
  - System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Type)
  langs:
  - csharp
  - vb
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Xaml.Markup.IValueSerializerContext
  type: Interface
  source:
    remote:
      path: src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
      branch: releases/OpenSilver/1.1.0
      repo: https://github.com/OpenSilver/OpenSilver.git
    id: IValueSerializerContext
    path: ../OpenSilverGit/src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
    startLine: 30
  assemblies:
  - OpenSilver.Xaml
  namespace: System.Xaml.Markup
  syntax:
    content: 'public interface IValueSerializerContext : ITypeDescriptorContext, IServiceProvider'
    content.vb: >-
      Public Interface IValueSerializerContext
          Inherits IServiceProvider, ITypeDescriptorContext
  inheritedMembers:
  - System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
  - System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
  - System.ComponentModel.ITypeDescriptorContext.Container
  - System.ComponentModel.ITypeDescriptorContext.Instance
  - System.ComponentModel.ITypeDescriptorContext.PropertyDescriptor
  - System.IServiceProvider.GetService(System.Type)
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Reflection.PropertyInfo)
  commentId: M:System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Reflection.PropertyInfo)
  id: GetValueSerializerFor(System.Reflection.PropertyInfo)
  parent: System.Xaml.Markup.IValueSerializerContext
  langs:
  - csharp
  - vb
  name: GetValueSerializerFor(PropertyInfo)
  nameWithType: IValueSerializerContext.GetValueSerializerFor(PropertyInfo)
  fullName: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Reflection.PropertyInfo)
  type: Method
  source:
    remote:
      path: src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
      branch: releases/OpenSilver/1.1.0
      repo: https://github.com/OpenSilver/OpenSilver.git
    id: GetValueSerializerFor
    path: ../OpenSilverGit/src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
    startLine: 32
  assemblies:
  - OpenSilver.Xaml
  namespace: System.Xaml.Markup
  syntax:
    content: ValueSerializer GetValueSerializerFor(PropertyInfo descriptor)
    parameters:
    - id: descriptor
      type: System.Reflection.PropertyInfo
    return:
      type: System.Xaml.Markup.ValueSerializer
    content.vb: Function GetValueSerializerFor(descriptor As PropertyInfo) As ValueSerializer
  overload: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor*
- uid: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Type)
  commentId: M:System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Type)
  id: GetValueSerializerFor(System.Type)
  parent: System.Xaml.Markup.IValueSerializerContext
  langs:
  - csharp
  - vb
  name: GetValueSerializerFor(Type)
  nameWithType: IValueSerializerContext.GetValueSerializerFor(Type)
  fullName: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor(System.Type)
  type: Method
  source:
    remote:
      path: src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
      branch: releases/OpenSilver/1.1.0
      repo: https://github.com/OpenSilver/OpenSilver.git
    id: GetValueSerializerFor
    path: ../OpenSilverGit/src/Runtime/OpenSilver.Xaml/System.Xaml.Markup/IValueSerializerContext.cs
    startLine: 33
  assemblies:
  - OpenSilver.Xaml
  namespace: System.Xaml.Markup
  syntax:
    content: ValueSerializer GetValueSerializerFor(Type type)
    parameters:
    - id: type
      type: System.Type
    return:
      type: System.Xaml.Markup.ValueSerializer
    content.vb: Function GetValueSerializerFor(type As Type) As ValueSerializer
  overload: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor*
references:
- uid: System.Xaml.Markup
  commentId: N:System.Xaml.Markup
  name: System.Xaml.Markup
  nameWithType: System.Xaml.Markup
  fullName: System.Xaml.Markup
- uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
  commentId: M:System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
  parent: System.ComponentModel.ITypeDescriptorContext
  isExternal: true
  name: OnComponentChanged()
  nameWithType: ITypeDescriptorContext.OnComponentChanged()
  fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged()
  spec.csharp:
  - uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
    name: OnComponentChanged
    nameWithType: ITypeDescriptorContext.OnComponentChanged
    fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
    name: OnComponentChanged
    nameWithType: ITypeDescriptorContext.OnComponentChanged
    fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanged
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
  commentId: M:System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
  parent: System.ComponentModel.ITypeDescriptorContext
  isExternal: true
  name: OnComponentChanging()
  nameWithType: ITypeDescriptorContext.OnComponentChanging()
  fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging()
  spec.csharp:
  - uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
    name: OnComponentChanging
    nameWithType: ITypeDescriptorContext.OnComponentChanging
    fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
    name: OnComponentChanging
    nameWithType: ITypeDescriptorContext.OnComponentChanging
    fullName: System.ComponentModel.ITypeDescriptorContext.OnComponentChanging
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ComponentModel.ITypeDescriptorContext.Container
  commentId: P:System.ComponentModel.ITypeDescriptorContext.Container
  parent: System.ComponentModel.ITypeDescriptorContext
  isExternal: true
  name: Container
  nameWithType: ITypeDescriptorContext.Container
  fullName: System.ComponentModel.ITypeDescriptorContext.Container
- uid: System.ComponentModel.ITypeDescriptorContext.Instance
  commentId: P:System.ComponentModel.ITypeDescriptorContext.Instance
  parent: System.ComponentModel.ITypeDescriptorContext
  isExternal: true
  name: Instance
  nameWithType: ITypeDescriptorContext.Instance
  fullName: System.ComponentModel.ITypeDescriptorContext.Instance
- uid: System.ComponentModel.ITypeDescriptorContext.PropertyDescriptor
  commentId: P:System.ComponentModel.ITypeDescriptorContext.PropertyDescriptor
  parent: System.ComponentModel.ITypeDescriptorContext
  isExternal: true
  name: PropertyDescriptor
  nameWithType: ITypeDescriptorContext.PropertyDescriptor
  fullName: System.ComponentModel.ITypeDescriptorContext.PropertyDescriptor
- uid: System.IServiceProvider.GetService(System.Type)
  commentId: M:System.IServiceProvider.GetService(System.Type)
  parent: System.IServiceProvider
  isExternal: true
  name: GetService(Type)
  nameWithType: IServiceProvider.GetService(Type)
  fullName: System.IServiceProvider.GetService(System.Type)
  spec.csharp:
  - uid: System.IServiceProvider.GetService(System.Type)
    name: GetService
    nameWithType: IServiceProvider.GetService
    fullName: System.IServiceProvider.GetService
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IServiceProvider.GetService(System.Type)
    name: GetService
    nameWithType: IServiceProvider.GetService
    fullName: System.IServiceProvider.GetService
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ComponentModel.ITypeDescriptorContext
  commentId: T:System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.IServiceProvider
  commentId: T:System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
- uid: System
  commentId: N:System
  name: System
  nameWithType: System
  fullName: System
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor*
  commentId: Overload:System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor
  name: GetValueSerializerFor
  nameWithType: IValueSerializerContext.GetValueSerializerFor
  fullName: System.Xaml.Markup.IValueSerializerContext.GetValueSerializerFor
- uid: System.Reflection.PropertyInfo
  commentId: T:System.Reflection.PropertyInfo
  parent: System.Reflection
  isExternal: true
  name: PropertyInfo
  nameWithType: PropertyInfo
  fullName: System.Reflection.PropertyInfo
- uid: System.Xaml.Markup.ValueSerializer
  commentId: T:System.Xaml.Markup.ValueSerializer
  parent: System.Xaml.Markup
  name: ValueSerializer
  nameWithType: ValueSerializer
  fullName: System.Xaml.Markup.ValueSerializer
- uid: System.Reflection
  commentId: N:System.Reflection
  name: System.Reflection
  nameWithType: System.Reflection
  fullName: System.Reflection
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
